// Source-backed catalog generated by scripts/product_agent.py.
const productsList = [
  {
    "name": "Apple AirPods 4 with Active Noise Cancellation",
    "category": "Audio",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple AirPods Pro 2",
    "category": "Audio",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Beats Studio Pro",
    "category": "Audio",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Bose QuietComfort Ultra Earbuds",
    "category": "Audio",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Bose QuietComfort Ultra Headphones",
    "category": "Audio",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Google Pixel Buds Pro 2",
    "category": "Audio",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "JBL Tour One M3",
    "category": "Audio",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Nothing Ear",
    "category": "Audio",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "OnePlus Buds Pro 3",
    "category": "Audio",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy Buds3 Pro",
    "category": "Audio",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Sennheiser Momentum 4 Wireless",
    "category": "Audio",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Sennheiser Momentum True Wireless 4",
    "category": "Audio",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Sonos Ace",
    "category": "Audio",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Sony WH-1000XM5",
    "category": "Audio",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Sony WH-1000XM6",
    "category": "Audio",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "ASUS ROG Ally X",
    "category": "Console",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Microsoft Xbox Series S 1TB",
    "category": "Console",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Microsoft Xbox Series X 1TB Digital Edition",
    "category": "Console",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Microsoft Xbox Series X 2TB Galaxy Black",
    "category": "Console",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Nintendo Switch 2",
    "category": "Console",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Sony PlayStation 5 Digital Edition",
    "category": "Console",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Sony PlayStation 5 Pro",
    "category": "Console",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Sony PlayStation 5 Slim",
    "category": "Console",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Valve Steam Deck OLED",
    "category": "Console",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "AMD Radeon RX 7900 XTX",
    "category": "GPU",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "AMD Radeon RX 9070",
    "category": "GPU",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "AMD Radeon RX 9070 XT",
    "category": "GPU",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Intel Arc A770",
    "category": "GPU",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Intel Arc B580",
    "category": "GPU",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "NVIDIA GeForce RTX 4070 SUPER",
    "category": "GPU",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "NVIDIA GeForce RTX 4080 SUPER",
    "category": "GPU",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "NVIDIA GeForce RTX 4090",
    "category": "GPU",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "NVIDIA GeForce RTX 5060",
    "category": "GPU",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "NVIDIA GeForce RTX 5060 Ti",
    "category": "GPU",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "NVIDIA GeForce RTX 5070",
    "category": "GPU",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "NVIDIA GeForce RTX 5070 Ti",
    "category": "GPU",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "NVIDIA GeForce RTX 5080",
    "category": "GPU",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "NVIDIA GeForce RTX 5090",
    "category": "GPU",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "ASUS ROG Strix SCAR 18",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "ASUS ROG Zephyrus G14",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "ASUS ROG Zephyrus G16",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "ASUS Zenbook S 14",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Acer Predator Helios 18 AI",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Acer Swift 14 AI",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Alienware m16 R2",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple MacBook Air 13-inch M5",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple MacBook Air 15-inch M5",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple MacBook Pro 14-inch M5",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple MacBook Pro 14-inch M5 Pro",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple MacBook Pro 16-inch M5 Max",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple MacBook Pro 16-inch M5 Pro",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Dell 14 Premium",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Dell 16 Premium",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Dell XPS 13 9350",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Framework Laptop 13",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Framework Laptop 16",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "HP OmniBook Ultra Flip 14",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "HP Spectre x360 14",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Huawei MateBook X Pro 2024",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "LG gram Pro 16",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Lenovo Legion Pro 7i Gen 10",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Lenovo ThinkPad X1 Carbon Gen 13",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Lenovo Yoga Slim 9i",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "MSI Stealth A16 AI+",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Microsoft Surface Laptop 7 13.8-inch",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Microsoft Surface Laptop 7 15-inch",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Razer Blade 14",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Razer Blade 16",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy Book5 Pro 14",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy Book5 Pro 16",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy Book5 Pro 360",
    "category": "Laptop",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "ASUS ROG Swift OLED PG32UCDM",
    "category": "Monitor",
    "display": "32-inch QD-OLED, 3840 x 2160",
    "cpu": null,
    "gpu": null,
    "ram": null,
    "storage": null,
    "battery": null,
    "camera": null,
    "connectivity": "2 HDMI 2.1, 1 DisplayPort 1.4, USB-C, USB 3.2 Gen 2",
    "weight": "13.2 pounds",
    "price": "{'amount': 1299, 'currency': 'USD', 'market': 'USA', 'as_of': '2023-10'}",
    "score": 90,
    "lastUpdated": "2026-07-24",
    "sources": [
      {
        "name": "PCMag",
        "url": "https://www.pcmag.com/reviews/asus-rog-swift-oled-pg32ucdm"
      },
      {
        "name": "TFTCentral",
        "url": "https://tftcentral.co.uk/reviews/asus-rog-swift-pg32ucdm"
      },
      {
        "name": "Forbes",
        "url": "https://www.forbes.com/sites/mitchwallace/2025/05/15/asus-rog-swift-32-4k-oled-gaming-monitor-pg32ucdm-review-delicate-power"
      },
      {
        "name": "Tom's Hardware",
        "url": "https://www.tomshardware.com/monitors/gaming-monitors/asus-rog-swift-pg32ucdm3-32-inch-240-hz-qd-oled-gaming-monitor-review"
      },
      {
        "name": "RTINGS.com",
        "url": "https://www.rtings.com/monitor/reviews/asus/rog-swift-oled-pg32ucdm"
      }
    ]
  },
  {
    "name": "Alienware AW2725DF",
    "category": "Monitor",
    "display": "27-inch QHD (2560 x 1440) QD-OLED",
    "cpu": null,
    "gpu": null,
    "ram": null,
    "storage": null,
    "battery": null,
    "camera": null,
    "connectivity": "2x DisplayPort 1.4, 1x HDMI 2.1, 1x USB 3.2 Type-B, 2x USB 3.2 Type-C, 1x USB 3.2 Type-A",
    "weight": null,
    "price": "{'amount': 799, 'currency': 'USD', 'market': 'USA', 'as_of': '2026-07-24'}",
    "score": 90,
    "lastUpdated": "2026-07-24",
    "sources": [
      {
        "name": "TweakTown",
        "url": "https://www.tweaktown.com/reviews/10867/alienware-aw2725df-gaming-monitor-peak-1440p-with-qd-oled-at-360hz/index.html"
      },
      {
        "name": "Dell USA",
        "url": "https://www.dell.com/en-us/shop/alienware-27-360hz-qd-oled-gaming-monitor-aw2725df/apd/210-bljd/monitors-monitor-accessories"
      },
      {
        "name": "Amazon",
        "url": "https://www.amazon.com/Alienware-AW2725DF-OLED-Gaming-Monitor/dp/B0CZSGWLD5"
      },
      {
        "name": "TFTCentral",
        "url": "https://tftcentral.co.uk/reviews/dell-alienware-aw2725df"
      },
      {
        "name": "RTINGS",
        "url": "https://www.rtings.com/monitor/reviews/dell/alienware-aw2725df"
      }
    ]
  },
  {
    "name": "Alienware AW3225QF",
    "category": "Monitor",
    "display": "32-inch QD-OLED, 3840 x 2160",
    "cpu": null,
    "gpu": null,
    "ram": null,
    "storage": null,
    "battery": null,
    "camera": null,
    "connectivity": "2 x HDMI 2.1, 1 x DisplayPort 1.4, USB-A 3.2, USB-C",
    "weight": "13 pounds",
    "price": "{'amount': 1199, 'currency': 'USD', 'market': 'USA', 'as_of': '2024'}",
    "score": 90,
    "lastUpdated": "2026-07-24",
    "sources": [
      {
        "name": "PCMag",
        "url": "https://www.pcmag.com/reviews/alienware-aw3225qf-4k-qd-oled"
      },
      {
        "name": "Tom's Hardware",
        "url": "https://www.tomshardware.com/monitors/gaming-monitors/alienware-aw3225qf-oled-4k-gaming-monitor-review"
      },
      {
        "name": "Laptop Mag",
        "url": "https://www.laptopmag.com/gaming/gaming-monitors/alienware-32-inch-4k-qd-oled-aw3225qf"
      },
      {
        "name": "TFTCentral",
        "url": "https://tftcentral.co.uk/reviews/dell-alienware-aw3225qf"
      },
      {
        "name": "PC Perspective",
        "url": "https://pcper.com/2024/04/alienware-aw3225qf-4k-qd-oled-monitor-review"
      }
    ]
  },
  {
    "name": "Apple Studio Display",
    "category": "Monitor",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "BenQ PD3225U",
    "category": "Monitor",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Dell UltraSharp U3225QE",
    "category": "Monitor",
    "display": "32-inch 4K UHD (3840 x 2160) with IPS Black technology",
    "cpu": null,
    "gpu": null,
    "ram": null,
    "storage": null,
    "battery": null,
    "camera": null,
    "connectivity": "Dual Thunderbolt 4 ports, HDMI 2.1, DisplayPort 1.4, multiple USB-C & USB-A ports, Ethernet, audio combo jack",
    "weight": "20.59 pounds",
    "price": "{'amount': 949.99, 'currency': 'USD', 'market': 'USA', 'as_of': '2025'}",
    "score": 90,
    "lastUpdated": "2026-07-24",
    "sources": [
      {
        "name": "PCWorld",
        "url": "https://www.pcworld.com/article/2618102/dell-ultrasharp-u3225qe-review-the-best-home-office-monitor-yet.html"
      },
      {
        "name": "Laptop Mag",
        "url": "https://www.laptopmag.com/gaming/gaming-monitors/dell-ultrasharp-32-4k-thunderbolt-hub-monitor-review"
      },
      {
        "name": "Dell USA",
        "url": "https://www.dell.com/en-us/shop/dell-ultrasharp-32-4k-thunderbolt-hub-monitor-u3225qe/apd/210-bqhs/monitors-monitor-accessories"
      },
      {
        "name": "Amazon",
        "url": "https://www.amazon.com/Dell-UltraSharp-32-inch-Thunderbolt-Monitor/dp/B0FDCLPZC6"
      },
      {
        "name": "YouTube Review",
        "url": "https://www.youtube.com/watch?v=auBJ2a57dDs"
      }
    ]
  },
  {
    "name": "Gigabyte AORUS FO32U2P",
    "category": "Monitor",
    "display": "31.5\" QD-OLED",
    "cpu": null,
    "gpu": null,
    "ram": null,
    "storage": null,
    "battery": null,
    "camera": null,
    "connectivity": "2x HDMI 2.1, 1x DP 2.1, 1x Mini-DP, 1x USB Type-C, 2x USB 3.2 Type-A, 1x USB Type-B, audio jack",
    "weight": "8.53 kg",
    "price": "{'amount': 999.99, 'currency': 'USD', 'market': None, 'as_of': '2026-07-24'}",
    "score": 90,
    "lastUpdated": "2026-07-24",
    "sources": [
      {
        "name": "Wccftech",
        "url": "https://wccftech.com/review/gigabyte-aorus-fo32u2p-4k-240hz-qd-oled-gaming-monitor-review-an-oled-stunner-with-full-dp2-1-bandwidth"
      },
      {
        "name": "Tom's Hardware",
        "url": "https://www.tomshardware.com/monitors/gaming-monitors/gigabyte-aorus-fo32u2p-240-hz-4k-oled-gaming-monitor-review"
      },
      {
        "name": "Geekawhat",
        "url": "https://geekawhat.com/gigabyte-aorus-fo32u2p-monitor-review"
      },
      {
        "name": "TechPorn",
        "url": "https://www.techporn.ph/gigabyte-aorus-fo32u2p-gaming-monitor-review"
      },
      {
        "name": "TFTCentral",
        "url": "https://tftcentral.co.uk/reviews/gigabyte-aorus-fo32u2p"
      }
    ]
  },
  {
    "name": "LG DualUp 28MQ780",
    "category": "Monitor",
    "display": "28-inch, 2560 x 2880, 16:18 aspect ratio",
    "cpu": null,
    "gpu": null,
    "ram": null,
    "storage": null,
    "battery": null,
    "camera": null,
    "connectivity": "USB-C, HDMI, DisplayPort",
    "weight": "4.3 kg",
    "price": "{'amount': '699', 'currency': 'USD', 'market': 'USA', 'as_of': '2022-01-16'}",
    "score": 75,
    "lastUpdated": "2026-07-24",
    "sources": [
      {
        "name": "PCWorld",
        "url": "https://www.pcworld.com/article/796390/lg-dualup-28mq780-b-monitor-review.html"
      },
      {
        "name": "Tom's Hardware",
        "url": "https://www.tomshardware.com/reviews/lg-28mw70-dualup-monitor"
      },
      {
        "name": "Versus",
        "url": "https://versus.com/en/lg-dualup-28mq780-b-27-6"
      },
      {
        "name": "HardwareZone",
        "url": "https://www.hardwarezone.com.sg/pc/accessories/review-lg-dualup-ergo-28mq780-b-square-work-office-monitor-review-price-specs-features-singapore"
      },
      {
        "name": "LG USA",
        "url": "https://www.lg.com/us/monitors/lg-28mq780-b-dualup-monitor"
      }
    ]
  },
  {
    "name": "LG UltraGear 32GS95UE",
    "category": "Monitor",
    "display": "32-inch 4K OLED",
    "cpu": null,
    "gpu": null,
    "ram": null,
    "storage": null,
    "battery": null,
    "camera": null,
    "connectivity": "HDMI 2.1, DisplayPort 1.4, USB 3.0 hub",
    "weight": null,
    "price": "{'amount': '$1,100 - $1,400', 'currency': 'USD', 'market': 'US', 'as_of': '2026-07-24'}",
    "score": 85,
    "lastUpdated": "2026-07-24",
    "sources": [
      {
        "name": "Display Ninja",
        "url": "https://www.displayninja.com/lg-32gs95ue-review"
      },
      {
        "name": "TechSpot",
        "url": "https://www.techspot.com/review/2822-lg-32gs95ue-woled"
      },
      {
        "name": "Amazon",
        "url": "https://www.amazon.com/LG-%E2%80%8E32GS95UE-Ultragear-DisplayHDR-DisplayPort/dp/B0CV1Y7NLT"
      },
      {
        "name": "LG USA",
        "url": "https://www.lg.com/us/monitors/lg-32gs95ue-b-gaming-monitor"
      },
      {
        "name": "TFTCentral",
        "url": "https://tftcentral.co.uk/reviews/lg-32gs95ue"
      }
    ]
  },
  {
    "name": "MSI MPG 321URX QD-OLED",
    "category": "Monitor",
    "display": "32-inch QD-OLED, 3840x2160 (UHD), 240Hz",
    "cpu": null,
    "gpu": null,
    "ram": null,
    "storage": null,
    "battery": null,
    "camera": null,
    "connectivity": "USB-C Display Port",
    "weight": null,
    "price": "$950, market unknown, as-of 2023",
    "score": 85,
    "lastUpdated": "2026-07-24",
    "sources": [
      {
        "name": "MSI Official Site",
        "url": "https://www.msi.com/Monitor/MPG-321URX-QD-OLED"
      },
      {
        "name": "YouTube Review",
        "url": "https://www.youtube.com/watch?v=z-U8MdpTuDE&vl=en"
      }
    ]
  },
  {
    "name": "Samsung Odyssey OLED G8 G80SD",
    "category": "Monitor",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Odyssey OLED G9 G95SD",
    "category": "Monitor",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung ViewFinity S9 S90PC",
    "category": "Monitor",
    "display": "27\" 5K (5120 x 2880) IPS",
    "cpu": null,
    "gpu": null,
    "ram": null,
    "storage": null,
    "battery": null,
    "camera": "4K SlimFit camera",
    "connectivity": "Thunderbolt 4, USB-C, Mini DisplayPort, Wi-Fi 5, Bluetooth 4.2",
    "weight": "7.4 kg",
    "price": "{'amount': '1599.99', 'currency': 'USD', 'market': 'US', 'as_of': '2023-09'}",
    "score": 85,
    "lastUpdated": "2026-07-24",
    "sources": [
      {
        "name": "Samsung Official Site",
        "url": "https://www.samsung.com/nz/monitors/high-resolution/viewfinity-s9-27-inch-5k-resolution-ls27c900paexxy"
      },
      {
        "name": "Microless",
        "url": "https://global.microless.com/product/samsung-viewfinity-s9-s90pc-smart-monitor-27-5k-5120-x-2880-ips-display-60hz-refresh-rate-5ms-gtg-response-time-wi-fi5-bt4-2-max-1b-color-built-in-2x-5w-speaker-silver-ls27c902pamxue?currency=usd"
      },
      {
        "name": "Six Colors Review",
        "url": "https://sixcolors.com/post/2023/09/review-27-inch-samsung-viewfinity-s9-display"
      },
      {
        "name": "TechPowerUp Review",
        "url": "https://www.techpowerup.com/review/samsung-viewfinity-s9"
      },
      {
        "name": "BGR Review",
        "url": "https://www.bgr.com/reviews/samsung-viewfinity-s9-review"
      }
    ]
  },
  {
    "name": "ASUS ROG Phone 9 Pro",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple iPhone 16",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple iPhone 16 Plus",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple iPhone 16 Pro",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple iPhone 16 Pro Max",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple iPhone 16e",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple iPhone 17",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple iPhone 17 Pro",
    "category": "Phone",
    "display": "6.3 inches, 2622 x 1206 pixels, 460 ppi, up to 3000 nits brightness",
    "cpu": "A19 Pro chip",
    "gpu": "6-core GPU with Neural Accelerators",
    "ram": "12GB",
    "storage": "256GB, 512GB, 1TB",
    "battery": null,
    "camera": "Triple rear cameras: 48MP ultra-wide, 48MP wide, 48MP 8x telephoto",
    "connectivity": "USB-C 3.0, 5G",
    "weight": "7.27 ounces",
    "price": "{'amount': 1099, 'currency': 'USD', 'market': 'USA', 'as_of': 'September 19, 2025'}",
    "score": 85,
    "lastUpdated": "2026-07-24",
    "sources": [
      {
        "name": "PCMag Middle East",
        "url": "https://me.pcmag.com/en/mobile-phones/32331/apple-iphone-17-pro"
      },
      {
        "name": "GSMArena",
        "url": "https://www.gsmarena.com/apple_iphone_17_pro-14049.php"
      },
      {
        "name": "AppleInsider",
        "url": "https://appleinsider.com/articles/25/12/17/iphone-17-pro-review-three-months-later-still-fresh"
      },
      {
        "name": "Wikipedia",
        "url": "https://en.wikipedia.org/wiki/IPhone_17_Pro"
      }
    ]
  },
  {
    "name": "Apple iPhone 17 Pro Max",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple iPhone 17e",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple iPhone Air",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Google Pixel 10",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Google Pixel 10 Pro",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Google Pixel 10 Pro XL",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Google Pixel 9a",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "HONOR Magic V3",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "HONOR Magic7 Pro",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Huawei Mate X6",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Huawei Pura 70 Ultra",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Motorola Edge 60 Pro",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Motorola Razr 60 Ultra",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Nothing Phone (3)",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Nothing Phone (3a) Pro",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "OPPO Find N5",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "OPPO Find X8 Pro",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "OnePlus 13",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "OnePlus 13R",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Redmi Note 14 Pro+ 5G",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy A56 5G",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy A57 5G",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy S25",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy S25 Ultra",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy S25+",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy S26",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy S26 Ultra",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy S26+",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy Z Flip7",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy Z Fold7",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Sony Xperia 1 VII",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Xiaomi 14T Pro",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Xiaomi 15",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Xiaomi 15 Ultra",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "vivo X200 Pro",
    "category": "Phone",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple iPad Air 11-inch M3",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple iPad Air 13-inch M3",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple iPad Pro 11-inch M5",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple iPad Pro 13-inch M5",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple iPad mini A17 Pro",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Google Pixel Tablet",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "HONOR MagicPad 2",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Huawei MatePad Pro 13.2",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Lenovo Yoga Tab Plus",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Microsoft Surface Pro 11",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "OnePlus Pad 2",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Redmi Pad Pro",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy Tab S10 FE",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy Tab S10 Ultra",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy Tab S10+",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Xiaomi Pad 7 Pro",
    "category": "Tablet",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple Watch SE 2",
    "category": "Wearable",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple Watch Series 10",
    "category": "Wearable",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Apple Watch Ultra 2",
    "category": "Wearable",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Fitbit Charge 6",
    "category": "Wearable",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Garmin Fenix 8",
    "category": "Wearable",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Garmin Forerunner 970",
    "category": "Wearable",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Garmin Venu 3",
    "category": "Wearable",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Google Pixel Watch 3",
    "category": "Wearable",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Huawei Watch GT 5 Pro",
    "category": "Wearable",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Oura Ring 4",
    "category": "Wearable",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy Ring",
    "category": "Wearable",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy Watch Ultra",
    "category": "Wearable",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Samsung Galaxy Watch7",
    "category": "Wearable",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "WHOOP 5.0",
    "category": "Wearable",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  },
  {
    "name": "Xiaomi Watch 2 Pro",
    "category": "Wearable",
    "status": "seed",
    "lastUpdated": null,
    "sources": []
  }
];
